<a href="https://colab.research.google.com/github/smitbajaj/phillies-learning/blob/main/marcel_toy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd
df = pd.read_csv("/content/batting.csv")

proj_yr = 2019
yearly_weights = {2016: 3, 2017: 4, 2018: 5}
prior_yrs = list(yearly_weights.keys())

# proj_stats = ["player_id","yr", "ab", "r", "h", "_1b", "_2b", "_3b", "hr", "rbi", "sb", "cs", "bb", "so", "ibb", "hbp", "sh", "sf", "gidp"]

proj_stats = ["ab", "r", "h", "_1b", "_2b", "_3b", "hr", "rbi", "sb", "cs", "bb", "so", "ibb", "hbp", "sh", "sf", "gidp"]

priors = df.query('yr in @prior_yrs').set_index(['player_id', 'yr'])

priors_weighted = pd.concat([(priors.query('yr==@yr') * weight) for yr, weight in yearly_weights.items()])
prior_weighted_avg = priors_weighted.groupby('player_id').sum()/sum(yearly_weights.values())

In [20]:
prior_weighted_avg

,pa,ab,r,h,_1b,_2b,_3b,hr,rbi,sb,cs,bb,so,ibb,hbp,sh,sf,gidp
player_id,,,,,,,,,,,,,,,,,,
abadfe01,0.250000,0.250000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000
abreujo02,629.166667,570.916667,76.75,163.750000,97.333333,37.333333,2.666667,26.416667,91.500000,1.833333,0.500000,38.833333,116.333333,6.666667,13.333333,0.000000,6.083333,18.083333
achteaj01,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ackledu01,17.500000,15.250000,1.50,2.250000,2.250000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.250000,0.000000,0.000000,0.000000,0.250000,0.000000
acunaro01,202.916667,180.416667,32.50,52.916667,29.583333,10.833333,1.666667,10.833333,26.666667,6.666667,2.083333,18.750000,51.250000,0.833333,2.500000,0.000000,1.250000,1.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zimmejo02,4.083333,3.833333,0.00,0.583333,0.583333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.666667,0.000000,0.000000,0.250000,0.000000,0.000000
zimmery01,443.333333,401.416667,58.75,107.916667,61.416667,24.250000,1.083333,21.166667,68.750000,1.750000,0.666667,34.416667,90.916667,1.000000,3.500000,0.000000,4.000000,12.500000
zobribe01,539.750000,465.333333,70.75,127.083333,85.750000,26.083333,3.000000,12.250000,59.833333,3.416667,3.333333,64.916667,69.166667,2.583333,2.500000,2.083333,4.916667,11.916667
zuninmi01,361.750000,325.416667,36.75,72.083333,34.833333,17.583333,0.000000,19.666667,47.416667,0.333333,0.000000,28.250000,132.083333,0.000000,6.666667,0.000000,1.416667,5.583333
zychto01,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [25]:
yearly_weights[2016]

3

In [ ]:
# priors = pd.read_csv('batting.csv').query('yr in @prior_yrs').set_index(['player_id', 'yr'])

hist_data = df[df['yr'].isin(prior_yrs)]
hist_data['weight'] = hist_data['yr'].map(yearly_weights)

weighted_sums = hist_data[proj_stats].multiply(hist_data['weight'], axis=0) # multiplying each stat column by 3, 4 or 5

weighted_totals = weighted_sums.groupby(hist_data['player_id']).sum() # gets all weighted totals for all stats

total_weights = hist_data.groupby('player_id')['weight'].sum() # calculates how much total weighting there is: (max: 3 + 4 + 5 = 12)

averaged_stats = weighted_totals.divide(total_weights, axis=0) # dividing the sum by this total weighting

averaged_stats.head(3)

In [60]:
lg_totals = hist_data.sum()
lg_avg = lg_totals[proj_stats]/lg_totals['pa']

In [62]:
lg_avg

ab      0.894882
r       0.118863
h       0.226188
_1b     0.145577
_2b     0.044901
_3b     0.004532
hr      0.031177
rbi     0.113372
sb      0.013585
cs      0.005214
bb      0.083986
so      0.216788
ibb     0.005102
hbp     0.009616
sh      0.004997
sf      0.006518
gidp    0.019788
dtype: object

In [50]:
test = hist_data.head(2)
test_2 = test[proj_stats].multiply(test['weight'], axis=0)
test_3 = test_2.sum()

total_weight = test['weight'].sum()
test_avg = test_total / total_weight

In [51]:
test_3

ab      3
r       0
h       0
_1b     0
_2b     0
_3b     0
hr      0
rbi     0
sb      0
cs      0
bb      0
so      3
ibb     0
hbp     0
sh      0
sf      0
gidp    0
dtype: int64

In [47]:
test

,player_id,yr,pa,ab,r,h,_1b,_2b,_3b,hr,...,sb,cs,bb,so,ibb,hbp,sh,sf,gidp,weight
0,abadfe01,2016,1,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,3
1,abadfe01,2017,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4

In [21]:
player_ids = list(set(hist_data['player_id']))